build:
  maxIssues: 0


style:
  active: false

config:
  warningsAsErrors: true

complexity:
  TooManyFunctions:
    thresholdInFiles: 30
    thresholdInClasses: 20
    ignorePrivate: true

output-reports:
  exclude:
    - 'TxtOutputReport'
    - 'XmlOutputReport'
    - 'MdOutputReport'